import Head from "next/head";
import Movies from "./movies/index";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/movies-icon.png" />
        <title>Movie Advicer</title>
      </Head>
      <main>
        <Movies />
      </main>
    </>
  );
}
