// import React from "react";
import Head from "next/head";
import Movies from "./movies/index";
import axios from "axios";
import { IMovieCardsProps } from "@/interfaces/imovies";
// import dbConnect from "../db/utils/dbConnect";
// import { useState } from "react";

export default function Home({movies}: IMovieCardsProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/movies-icon.png" />
        <title>Movie Advicer</title>
      </Head>
      <main>
        <Movies movies={movies} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const response = await axios.get('http://localhost:3000/api/movies');
  const movies = response.data;

  return {
    props: {
      movies,
    },
  };
}
